### ISSUE TITLE
Java Applet not loading on site "http://www.phy.ntnu.edu.tw/"

### ISSUE THREAD

**Issue by felipedutra13** [leaningtech/cheerpj-applet-runner#45]
Hi,

When i run the app, it appears the cheerPj logo, and then it's only a white page. It seems the applet is not loading.

![image](https://user-images.githubusercontent.com/20544661/119840765-a62cc800-bedb-11eb-8775-8dde4f9e3d05.png)

http://www.phy.ntnu.edu.tw/ntnujava/index.php?topic=19.0

Thanks

**Comment by marsicplusplus** [comment]
Hi @felipedutra13 

I have looked into it and it appears that this issue is connected to something we had already noticed in the past.

We have added this to our internal bug tracker and we will work on this as soon as possible for us, we will contact you when this will be solved.

Thanks for your reporting.

**Comment by alexp-sssup** [comment]
This applet is fixed in version `2024.10` of the CheerpJ Applet Runner extension. This new version is based on CheerpJ 3.0 architecture and brings many improvements to performance and robustness.
